package com.zzy.exception01;

public class Test {
    public static void main(String[] args) {
        int num1 = 10;
        int num2 = 0;



        System.out.println("程序继续执行...");
    }
}
